version: "3.8"

services:
  db:
    image: postgres
    restart: always
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pgdb
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d